name: Dark Ride
favicon: null
layout_spectrum: 0.33173
typography_spectrum: 0.26429
title: Dark Ride
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2b2b2b'
    - '#7d7d7d'
    - '#aaaaaa'
  brandStrength: 0
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
