typography_spectrum: 0.66525
color:
  brandColors:
    - '#101b2d'
    - '#385e9f'
    - '#73cade'
    - '#6191a7'
    - '#fcfeff'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Dark Ride
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Dark Ride
purpose: []
