name: Dark Ride
favicon: null
layout_spectrum: 0.8516
typography_spectrum: 0.45454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2b2b2b'
    - '#7d7d7d'
    - '#aaaaaa'
  brandStrength: 0.375
  lightness: 0.7076819241046906
  saturation: 0.1875
  rhythmicContrast: 0.3471916578710079
purpose: []
